name: Radosław Szeja Blog
description: iOS related articles
meta_description: "Radosław Szeja Blog"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://rszeja.me'
google_analytics: 'UA-XXXXXXXX-X'
disqus: true
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://rszeja.me'
author:         'Radosław Szeja'
authorTwitter:  'rad3ks'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
